### ISSUE TITLE
Namespace name cannot be found

### ISSUE THREAD

**Issue by Defraraver** [peterhuene/sqlite-net-wp8#10]
My problem is, i settled up everything corrently, but functions are missing. Looks like some functions don't work. i do have everything referenced and sqlite fork installed correctly too.(namespace name SQLiteAsyncConnection could not be found (are you missing a directive or an assembly reference?) , ive made a post on stackoverflow...i really tryed everything but i dont know whats wrong.

stackoverflow: http://stackoverflow.com/questions/16679191/windows-phone-8-sqlite-setup

**Comment by peterhuene** [comment]
Followed up with a comment on StackOverflow.

**Comment by peterhuene** [comment]
Closing as this issue has been resolved on StackOverflow.  Thanks!
