### ISSUE TITLE
Sqlite return stmt problems

### ISSUE THREAD

**Issue by Defraraver** [peterhuene/sqlite-net-wp8#11]
Hi, i ended up with a problem again, this time inside the SQLite.cs file, looks like the return stmt is causing the problem, i can show you the picture of the problem here: http://shrani.si/f/1y/5d/1pwmFsIw/problem2.jpg

another thing:
I followed a guide where thers code in the app.xaml.cs, the code seems to be copying the sqlite database file from the instalation folder to the local folder. (Is this necessary for the application to run properly?). In any case i get the following error: http://shrani.si/f/3j/gj/4qw0dh1/problem1.jpg

Thanks for helping.

**Comment by peterhuene** [comment]
Hi Defraraver,

The first issue is not the return statement but the throw two lines above it and it is likely an issue with the passed in query.  I would turn on first chance exceptions (i.e. "when thrown") for SQLite.SQLiteException in Debug -> Exceptions and see if you can inspect the result and query.  Likely something is wrong with the query.

The second issue is likely that GetResourceStream is returning null.  Assuming you wanted to copy over a prepopulated database that was built as a resource, did you ensure the DigMate.sqlite was added to your project as a resource and that it's relative path from the project directory matches the path you're passing into GetResourceStream?

As neither issue seems related to sqlite-net-wp8, I'm going to close this issue.  Feel free to open the issue again if it relates to sqlite-net-wp8.

Cheers.
