### ISSUE TITLE
Could not build under VS2013

### ISSUE THREAD

**Issue by lessneek** [peterhuene/sqlite-net-wp8#14]
When building in VS2013 with Win32 target platform.

> 1>------ Build started: Project: Sqlite, Configuration: Debug Win32 ------
> 1>  pch.cpp
> 1>  SqliteWP8.cpp
> 1>LINK : fatal error LNK1104: cannot open file 'sqlite3.lib'
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Though if change target platform to ARM build succeeds.

**Comment by lessneek** [comment]
Somehow I found the problem, under VS2013 with platform Win32 there is no $(PlatformTarget) variable, but there is $(PlatformShortName).
I have added 

> $(FrameworkSDKRoot)....\Windows Phone\v8.0\ExtensionSDKs\SQLite.WP80\3.7.17\DesignTime\$(PackageConfiguration)\$(PlatformShortName)

to the library directories and now build succeeds for Win32 platform.

**Comment by peterhuene** [comment]
When VS2013 gets closer to RTM and people start supporting it in their extensions (last I checked I had to manually update SQLite's extension's manifest to get it to install), I'll make sure this works with VS 2013.  Leaving this issue open as a reminder.

**Comment by peterhuene** [comment]
I was able to build using VS 2013 RC when I manually installed the latest SQLite for Windows Phone extension after downloading it from http://visualstudiogallery.msdn.microsoft.com.  I didn't have to modify the extension's manifest this time.  It worked just fine.
