### ISSUE TITLE
SQLLite 3.8.0

### ISSUE THREAD

**Issue by geniovi** [peterhuene/sqlite-net-wp8#19]
I updated SQL LITE 3.8 and receive erros, What should I upgrade?
Thank you

**Comment by peterhuene** [comment]
I'll push up a fix shortly.

**Comment by geniovi** [comment]
Ok thanks

**Comment by peterhuene** [comment]
The update has been pushed.

**Comment by geniovi** [comment]
Perfect thanks

**Comment by geniovi** [comment]
I'm sorry if i add a project in a my solutions receive errors:
this is image:
https://dl.dropboxusercontent.com/u/26312884/errors.png

why?
thank you

**Comment by peterhuene** [comment]
Make sure you pull the latest from master and restart VS.  It seems the VC++ project system has some problems with caching project file contents if they failed to load the first time, despite asking it to "reload project".

**Comment by geniovi** [comment]
I'm restart Visual Studio 2012 and also pc. but nothing, I also think it's a cache problem
I also tried to load it in another project, but nothing
how can I do?
thank you

**Comment by peterhuene** [comment]
Does your .vcxproj have references to 3.7.17 or 3.8.0?

**Comment by geniovi** [comment]
I solved re-reading project from github.  I changing the target path and it worked
thanks so much
