### ISSUE TITLE
Extension version 3.7.5.12

### ISSUE THREAD

**Issue by fmarquezs** [peterhuene/sqlite-net-wp8#2]
There is a new Visual Studio extension that updates SQLite to 3.7.15.2. I modified my local repository easily, and it seems to be working. I cannot commit my changes but I guess that the master version will have to be updated to be in sync.

**Comment by peterhuene** [comment]
I'll try to get it updated today, although I don't have access to a
computer until late evening EST.  Thanks for letting me know.
