### ISSUE TITLE
SQLite.cs errors

### ISSUE THREAD

**Issue by Jali2GitHub** [peterhuene/sqlite-net-wp8#20]
Hello,
I am testing sqlite-net-WP8 but have trouble getting it to work. When compiling my SQLite solution, I get three errors related to SQLite.cs, see below. Have tried with the previous versions but get the same error, the last one is from sqlite-net-WP8-3.8.0.zip.

Source line 12
The best overloaded method match for 'SQLite.SQLite3.Open (string, out Sqlite.Database, int, System.IntPtr)' has some invalid arguments
Source line 26
Line 12Argument 1: can not convert from 'byte []' to 'string'
Source line 32
'System.Threading.Thread' does not containe a definition for 'VolatileWrite'

I have performed the steps described for using sqlite-net-WP8 but probably done something wrong. Grateful if you can help me.

Regards
Jan Lindgren
jl@nybyit.se

**Comment by peterhuene** [comment]
Hi Jan,

Please make sure that SILVERLIGHT and USE_WP8_NATIVE_SQLITE are set in your compiler conditional symbols in your project settings.

**Comment by Jali2GitHub** [comment]
Hi Peter,
Thank you for your quick response and guidance, there was a misspelling in the project settings.

Do you know of any example, tutorial or similar that can help me create a simple test case. I have 
previously used SQLite in the PC environment.

Sincerely.
Jan Lindgren
jl@nybyit.se

 2013-09-03 peterhuene  wrote:

Hi Jan,

**Comment by peterhuene** [comment]
I don't know of any example or tutorial offhand, but using sqlite-net from WP8 should (primarily) be the same as from a desktop environment.  Check out [sqlite-net's page](https://github.com/praeclarum/sqlite-net) that has a few examples to get you started.
