### ISSUE TITLE
Imported projects SQLite.WP80.props not found

### ISSUE THREAD

**Issue by tofutim** [peterhuene/sqlite-net-wp8#21]
Dear Peter,

Thanks for your work on this project. When I try to import Sqlite.vcxproj into my solution I get:

D:\Projects\MvvmCross\sqlite-net-wp8\Sqlite.vcxproj(56,5): The imported project "C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v8.0\ExtensionSDKs\SQLite.WP80\3.8.0\DesignTime\CommonConfiguration\Neutral\SQLite.WP80.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

I tried uninstalling my SQLite Phone vsix and reinstalling the latest version to no avail. Oh... but wait, I think the latest is 3.8.x not .0. Perhaps that is the issue?

**Comment by peterhuene** [comment]
Looks like sqlite has been updated again.  This whole extensions thing is a game of whack-a-mole, so I'll update the project with the newer reference shortly.

**Comment by tofutim** [comment]
Thanks for responding so quickly. I wonder if there is a better way to do this. My folder says 3.8.0.2 - but I'm working on my own build of SQLite that may have a different number. Is there a way to make this version insensitive?

_Update_ I wonder if the issue is SQLite's on where it places the goods.

**Comment by peterhuene** [comment]
None that I know of.  If you figure something out please let me know.

**Comment by tofutim** [comment]
Peter, do you just edit the vcxproj directly?

**Comment by peterhuene** [comment]
Yep :).  I've pushed up version 3.8.0.2.

**Comment by tofutim** [comment]
Thanks you beat me to it!

**Comment by peterhuene** [comment]
Thanks for letting me know about the extension update; I don't get to monitor it that closely as I'm currently heads down on iOS development.

**Comment by ravensorb** [comment]
I am running into this issue now.  Is this something easy to fix?
