### ISSUE TITLE
SQLite Upgrade to 3.8.1

### ISSUE THREAD

**Issue by FransCRe** [peterhuene/sqlite-net-wp8#24]
Peter, 

Appreciate your effort to keep this library updated. 

Microsoft just update the SQLite version in their Visual Studio.(Express) 
for WindowsPhone8.

Thanks.

**Comment by peterhuene** [comment]
Upgraded to 3.8.1.  Going to also investigate VS 2013 now that it's RTM too (will probably create a "VS2013" branch since the extensions differ).

**Comment by FransCRe** [comment]
HI Peter,

To Create and Access a Sqlite dbase on the windows8 phone in the ISOlated storage in a secure way, seems to be more challenging then I thought.

Would you be able to give me a link to a code sample of a Windows  application where a SQLite database is created on the phone? 

Application Code is being written in C++.

Thx in advance,

Frans Reitsma

Gesendet von Windows-Mail

Von: peterhuene
Gesendet: ‎Freitag‎, ‎18‎. ‎Oktober‎ ‎2013 ‎07‎:‎16
An: peterhuene/sqlite-net-wp8
Cc: FransCRe

Upgraded to 3.8.1. Going to also investigate VS 2013 now that it's RTM.
