### ISSUE TITLE
Doesn't work with VS13

### ISSUE THREAD

**Issue by sarkanya** [peterhuene/sqlite-net-wp8#26]
If i want to add the project to the solution Visual Studio 2013 freezes.

**Comment by peterhuene** [comment]
I'm unable to reproduce this problem on my Windows 8.1 VM with VS 2013 installed.  Of course, Visual Studio hanging is a bug in Visual Studio, but did you install the extension from [SQLite's download page](http://www.sqlite.org/download.html) (the extension doesn't yet appear to be in 2013's gallery)?

**Comment by sarkanya** [comment]
Yes, I installed from there. And when i'm trying to add the project it starts loading but it never finishes. In vs12 it works fine.

**Comment by peterhuene** [comment]
Can you open the sqlite-net-wp8 project without adding it to an existing solution? When VS hangs, do you get a Windows Error Reporting dialog saying VS is no longer responding or does it just go unresponsive indefinitely?

**Comment by sarkanya** [comment]
I can open it without solution. It just stuck and loading while says: Please wait while project information is being loaded... After a while it says vs is no longer responding.

**Comment by peterhuene** [comment]
Unfortunately I don't know how I can help you investigate this issue.  The project should obviously not cause Visual Studio to hang and, thus far, your report is the only one I have of it doing so.  I hate to be the "just reboot it" guy here, but perhaps it's worth trying to repair your VS installation?

**Comment by sarkanya** [comment]
I tried to repair the installation, but it didn't resolve the problem. So i reinstalled the whole computer but stil, it won't work. I can open the project without including, but when i want to build it it freezes.

**Comment by sarkanya** [comment]
I found the problem: it has something to do with the telerik radcontrols. When i uninstalled it, it worked fine..

**Comment by peterhuene** [comment]
I'm glad to hear you worked it out. Thanks for closing out the issue.
