### ISSUE TITLE
Upgrade reference of SQLite SDK when installing the package

### ISSUE THREAD

**Issue by jagui** [peterhuene/sqlite-net-wp8#28]
Hi Peter,
kudos for putting together the nuget package, it's simplifying my team's work a lot.

I have one suggestion for you. Do you think it might be possible to update SDK reference when installing the package?

Currently we have to manually change it, see the following diff:

```
-    <SDKReference Include="SQLite.WP80, Version=3.8.2">
+    <SDKReference Include="SQLite.WP80, Version=3.8.3">
```

Cheers,
Juan

**Comment by peterhuene** [comment]
Is this `SDKReference` in the project you're referencing the `sqlite-net-wp8` nuget package from?  If so, is this required for you to do?  It shouldn't be for building your project, at least.

**Comment by jagui** [comment]
you're right, that's a sqlite-net dependency. 

Closing, thanks!
