### ISSUE TITLE
New Sqlite Version

### ISSUE THREAD

**Issue by ncipollina** [peterhuene/sqlite-net-wp8#33]
I just noticed that there is a new Sqlite version, 3.8.4.2.  Could you provide an updated NuGet package?

**Comment by peterhuene** [comment]
@ncipollina I'll try to push one out tonight.  Thanks for letting me know, as I don't use WP8 as much as I used to.

**Comment by erikcsik** [comment]
Hey!
@peterhuene  Are there any news about the update? Thanks!

**Comment by peterhuene** [comment]
@erikcsik Sorry for the delay.  I was traveling this past weekend and this sort of slipped off my radar.  I'm going to set aside a little time this afternoon to update things.  Thanks for your patience.

**Comment by peterhuene** [comment]
I've upgrade the nuget package to 3.4.8.2.  Please let me know if you have any problems.  Thanks!
