### ISSUE TITLE
Relationships

### ISSUE THREAD

**Issue by matewoj** [peterhuene/sqlite-net-wp8#35]
Hello

I would like to know, if it is possible to create relationships between entities by using sqlite-net-wp8.

**Comment by peterhuene** [comment]
Hi @frenc,

That's more of a question for [sqlite-net](https://github.com/praeclarum/sqlite-net), as sqlite-net-wp8 is simply an interop layer that sits between sqlite-net and sqlite3.dll.  I would try searching or opening an issue on sqlite-net.  Thanks!
