### ISSUE TITLE
Error while submitting an app to the store

### ISSUE THREAD

**Issue by vijayst** [peterhuene/sqlite-net-wp8#4]
While submitting an app to the store, I get an error - Native API not allowed. The error message is pasted in the image below.
![Sqlite](https://f.cloud.github.com/assets/3457565/241144/1b785cda-8990-11e2-83d4-f4194a67bf3c.png)

**Comment by peterhuene** [comment]
That's strange.  We are definitely using it in one of our published store apps.  MS was also looking into creating a NuGet package for this wrapper, so I would assume they would greenlight sqlite3.dll for the store (even more so as it's pretty much the only way to share a relational storage format between WP8 and Windows 8).

**Comment by peterhuene** [comment]
Seems similar to this thread: http://social.msdn.microsoft.com/Forums/en-US/wpdevelop/thread/394562f0-31ff-459f-902d-1c50c2d0e7b4/

Are you deploying the ARM build to the store?

**Comment by vijayst** [comment]
Thanks for the reply. The ARM build resolved it. I forgot to update the
issue after that.

Vijay

On Tuesday, 19 March 2013, peterhuene wrote:

> Seems similar to this thread:
> http://social.msdn.microsoft.com/Forums/en-US/wpdevelop/thread/394562f0-31ff-459f-902d-1c50c2d0e7b4/
> 
> Are you deploying the ARM build to the store?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/peterhuene/sqlite-net-wp8/issues/4#issuecomment-15132707
> .

## 

Sent from Gmail iPad app

**Comment by vijayst** [comment]
Hey,

I created the petition "NASSCOM: Stop blacklisting of employees" and wanted to see if you could help by adding your name.

Our goal is to reach 100 signatures and we need more support. You can read more and sign the petition here:

https://www.change.org/petitions/nasscom-stop-blacklisting-of-employees?share_id=eJuaSkJmtz&utm_source=share_petition&utm_medium=email&utm_campaign=petition_invitation

Thanks!
Vijay

You&#x27;re receiving this message because Vijay Thirugnanam sent you an email through Change.org&#x27;s petition sharing tool. Change.org has not stored your email address. If you believe you have received this message in error, respond directly to Vijay Thirugnanam at vijayst@gmail.com.
