### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ghost** [peterhuene/sqlite-net-wp8#6]
Hello,

I'm trying to build test app with sqlite-net-wp8 project but during the compilation I see this error:
Error   1   error C1510: Cannot load language resource clui.dll.    C:\test\projects\PhoneApp1\sqlite-net-wp8-master\CL Sqlite
Error   2   Metadata file 'C:\test\projects\PhoneApp1\Debug\Sqlite\Sqlite.winmd' could not be found C:\test\projects\PhoneApp1\PhoneApp1\CSC    PhoneApp1

How can I resolve this problem?

Thank you.

**Comment by peterhuene** [comment]
The first error message, the one about clui.dll, is the root problem.  CL (Microsoft's C++ compiler) can't find its resource DLL.  As a result, it's not even compiling the sqlite-net-wp8 source code resulting in the other cascading error messages.  This is likely an installation issue with Visual Studio; I would try repairing the installation.
