### ISSUE TITLE
Broken support for SQLite 3.7.16.1 

### ISSUE THREAD

**Issue by louy** [peterhuene/sqlite-net-wp8#7]
Hello,

I've just upgraded the SQLite plugin for VS to version 3.7.16.1 and the sqlite-net-wp8 project isn't working anymore.

I've removed the project from my solution and tried to re-add it but i'm getting an error

> "Unable to read the project file ... the imported project "...SQLite.WP80\3.7.16\DesignTime\CommonConfiguration\Neutral\SQLite.WP80.props" was not found. Confirm that the path in the <Import> declaration is correct..."

Is there anyway to download the old version of the sqlite plugin until this is fixed?

**Comment by louy** [comment]
This is actually weird after the latest commit! but i'm sure I've pulled the latest version from github :)

**Comment by louy** [comment]
The issue was fixed by closing and re-opening VS!

Looks like it was caching the project file somewhere.

I'm closing this issue now, sorry for this :)

**Comment by peterhuene** [comment]
Yeah, it seems VC++ incorrectly cache some of the project's information, so after modifying the paths by hand (their extension upgrade experience is crap), I always have to restart VS for them to take effect.  Glad you got it working.
