### ISSUE TITLE
Out-of-the-box error

### ISSUE THREAD

**Issue by tofutim** [peterhuene/sqlite-net-wp8#8]
Hi, I tried to add the project to an existing solution and got. In my case my extensions are installed elsewhere - which is probably the issue.

```
---------------------------
Microsoft Visual Studio
---------------------------
Unable to read the project file "Sqlite.vcxproj".

D:\Loqu8\smelt\sqlite-net-wp8\Sqlite.vcxproj(56,5): The imported project "C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v8.0\ExtensionSDKs\SQLite.WP80\3.7.16.1\DesignTime\CommonConfiguration\Neutral\SQLite.WP80.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
---------------------------
OK   
---------------------------
```

**Comment by tofutim** [comment]
Aha, on my end, it is 3.7.17

**Comment by peterhuene** [comment]
Yeah, this happens whenever the extension updates (or if you're unfortunate enough to be running a 32-bit OS, or on a different root drive, etc.).  The whole extension experience is...not good, let's say.  I see 3.7.16.1 as the current version on sqlite's website, though.  VS is not prompting me to update the extension to 3.7.17.

**Comment by peterhuene** [comment]
My recommendation is to manually edit the project file for now to point at the correct path.  It's what I have to do whenever the version bumps, I just push the change up when I run into it.

Also, you many need to update sqlite3.h in the Headers directory to be matching the extension version as well.  I tend to grab the sqlite amalgamation header from the latest version, but I don't see 3.7.17 yet (preview version?)

**Comment by peterhuene** [comment]
What I really should do is grab the lib and dll out of this vsix extension nonsense and stick them under git and rev them independently of the extension.

**Comment by tofutim** [comment]
That would be cool. In this case it is my own fault for compiling my own
vsix.

**Comment by peterhuene** [comment]
The extension is now updated to 3.7.17.
