### ISSUE TITLE
The project cannot be loaded after the update of SQLite.WP80 to version 3.7.17

### ISSUE THREAD

**Issue by continienzo** [peterhuene/sqlite-net-wp8#9]
Now if I try to import the existing project, a popup error appear: " Unable to read the project file Sqlite.vcxproj .... The imported project "C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v.8.0\ExtensionSDKs\SQLite.WP80\3.7.16.2\DesignTime\CommonConfiguration\Neutral\SQLite.WPLite.WP80.props was not found. COnfirm that the path in the <Import> declaration is correct, and that the file exists on disk".
In fact now the extension is in an other directory (C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v8.0\ExtensionSDKs\SQLite.WP80\3.7.17). 
How can I solve the problem if I could't open the project?

**Comment by continienzo** [comment]
I tried to copy all the content of ...\3.7.17 in a directory with the old name version (...\3.7.16.2) and I could load the project in my solution and it compiles without errors and it runs.
I notice that in the sqlite3.h  There is an hard coded  #define SQLITE_VERSION        "3.7.16.2"

**Comment by peterhuene** [comment]
I'll update the project in a few minutes.

**Comment by peterhuene** [comment]
Updated the sources to 3.7.17.

**Comment by continienzo** [comment]
Thank you Peter!

2013/5/21 peterhuene notifications@github.com

**Comment by peterhuene** [comment]
Any time!
